### ISSUE TITLE
Using Open Budget for other budgets?

### ISSUE THREAD

**Issue by emdeex** [robbiewain/theopenbudget#2]
Hi, first off, congrats, this is great visualisation.

It seems to be updated for the 2016-2017 Australian Govt Budget, is that right, and did that happen automatically, or did someone update it?

If I had a budget data set from a business, and I wanted to visualise it the same way... what would I need to do?  Any tips appreciated,

regards,
Murray

**Comment by robertdapice** [comment]
Hey Murray,

We manually updated for 16-17 budget using the updated government data series. It just means swapping in an updated csv file and a few html tweaks.

If you create a csv file in the same format as the one in this repo you should be able to make your own very easily. You might need to do a little html tweaking too!
