### ISSUE TITLE
Help debugging install issues?

### ISSUE THREAD

**Issue by emdeex** [robbiewain/theopenbudget#3]
Hi, I'm trying to setup my own local version, with the intention of getting this working with some other types of public budgets.

I'm installing on Windows 10 x64,,,

The npm install script seems to find errors in loading various modules... can you advise?

regards,
Murray

-------

C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master>npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated find-file@0.1.4: Use the globby package instead

> pngquant-bin@0.3.5 postinstall C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\pngquant-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/pngquant-bin/v0.3.5/vendor/win/pngquant.exe',
  name: 'pngquant.exe',
  os: 'win32' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:801:5)
    at C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\download\index.js:35:43
    at each (C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\each-async\each-async.js:63:4)
    at module.exports (C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\download\index.js:33:5)
    at C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\bin-wrapper\index.js:108:20
    at C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\bin-wrapper\index.js:141:24
    at C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\bin-check\index.js:30:20
    at C:\Users\emdee\Downloads\theopenbudget-master\theopenbudget-master\node_modules\executable\index.js:39:20
    at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN install:pngquant-bin@0.3.5 pngquant-bin@0.3.5 postinstall: `node index.js`
npm WARN install:pngquant-bin@0.3.5 Exit status 1

**Comment by emdeex** [comment]
I've solved a lot of issues by adding more dependencies to 'package.json'.

`  "name": "theopenbudget",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "imagemin-gifsicle": "^2.0.0",
    "imagemin-jpegtran": "^2.0.0",
    "imagemin-optipng": "^2.0.1",
    "imagemin-svgo": "^2.0.0",
	"imagemin-pngquant": "^2.0.0",
    "grunt": "~0.4.1",`

But I'm still getting a lot of warnings when running npm install...

`npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated find-file@1.0.1: Use the globby package instead
npm WARN prefer global jshint@2.4.4 should be installed with -g`

grunt serve will run, but the output doesn't fully work, there are no charts...

**Comment by robertdapice** [comment]
@robbiewain do you have any ideas on this?

**Comment by robbiewain** [comment]
Glad you got it sorted out, @emdeex.

I've just bumped some dependency versions in the package.json (ba535c3). Does the recent grunt-contrib-imagemin version fix this?

**Comment by emdeex** [comment]
Thanks @robbiewain .. I downloaded that new repo and it runs through fine
now, I'd say you've fixed it.

**Comment by robertdapice** [comment]
👍
